// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBBuPXFJEeXCJRMTpX_5GZUwxB2S1XDX94',
    appId: '1:496310139083:web:1bbca81aa2367ea8a8434e',
    messagingSenderId: '496310139083',
    projectId: 'fire1-87dcf',
    authDomain: 'fire1-87dcf.firebaseapp.com',
    storageBucket: 'fire1-87dcf.appspot.com',
    measurementId: 'G-RRP24CC4P2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC60P2XSIwlmCe6gTdmevL6TpTNcjjO8WI',
    appId: '1:496310139083:android:d855f68466c4c3dda8434e',
    messagingSenderId: '496310139083',
    projectId: 'fire1-87dcf',
    storageBucket: 'fire1-87dcf.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC-nAtqK31rQO46UUm5ErRqapidCBHrJHQ',
    appId: '1:496310139083:ios:98c213ff829f5c69a8434e',
    messagingSenderId: '496310139083',
    projectId: 'fire1-87dcf',
    storageBucket: 'fire1-87dcf.appspot.com',
    iosClientId: '496310139083-kkgfdalavourci0b73utbknf0jgme4ch.apps.googleusercontent.com',
    iosBundleId: 'com.example.untitled',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC-nAtqK31rQO46UUm5ErRqapidCBHrJHQ',
    appId: '1:496310139083:ios:b96ddd520a0ee3e4a8434e',
    messagingSenderId: '496310139083',
    projectId: 'fire1-87dcf',
    storageBucket: 'fire1-87dcf.appspot.com',
    iosClientId: '496310139083-qisohp9tog99b6r65quikguftnhpevmm.apps.googleusercontent.com',
    iosBundleId: 'com.example.untitled.RunnerTests',
  );
}
